Bookstore styling
katfogy/bookstore-react pull request #6
Opened 2023-06-16 09:17 UTC by katfogy

Add styling to the Bookstore project

2023-06-16 09:49 UTC, topeogunleye reviewed
Hi @katfogy, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't follow the template given at all.



|  |  |
| ------------- | ------------- |
| Your Design | <img width="960" alt="image" src="https://github.com/katfogy/bookstore-react/assets/52934128/04839bf1-0fb5-4e1d-bb8f-df9e69d51f12">  |
| Zeplin Design | ![image](https://github.com/katfogy/bookstore-react/assets/52934128/0466daa8-7458-405c-94db-65aaf3b797a7)  |

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-16 21:35 UTC, 1GORDON requested changes
##
## Hi @katfogy ✋

Good job so far!

## Highlights!
- Great use of Gitflow ✔️
- Professional Linter setup ✔️
- Professional readme ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 21:35 UTC, 1GORDON commented on src/App.css
> +}
Great design @katfogy 🤝

- [ ] As stated in the project requirements, kindly do not repeat the same rule for multiple styles. Instead, create a single class and reuse this class instead. You may create classes for the following repeating rules which include. `background-color: #ffff;`, `display: flex;`, and `list-style-type: none;`.

2023-06-16 21:35 UTC, 1GORDON commented on src/App.css
> +}
Great job so far @katfogy 🤝

- [ ] As stated in the project requirements. Kindly ensure your UI design is a replica of the design that was given. Kindly ensure the margins, color, and spacing of all the elements are an imitation of the Zeplin design given. 
- Your design
![your design](https://github.com/katfogy/bookstore-react/assets/63917725/7460ba73-aa98-415b-848f-09d312457b67)
- Given design
![Given design](https://github.com/katfogy/bookstore-react/assets/63917725/d01d1ff1-e882-41c4-841a-d8fd8cf7a962)
You may also check out this [link](https://github.com/microverseinc/curriculum-react-redux/blob/main/bookstore/images/bookstore.png) to look at the design provided.

2023-06-17 00:00 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @katfogy 

Good job so far! I really appreciate the effort you put in!  **_However, there are few this that still need to be fixed. But you are almost there!_** 💪 🏁

![so close](https://media.tenor.com/3sCHnD_x2RIAAAAC/almost-there.gif)

## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ Good job with the design
- ✅ Great job with CSS
- ✅ Descriptive PR title
- ✅ Correct Linters

## Required Changes 🛑

_Please check the comments under the review._

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-17 00:00 UTC, KanzaTahreem commented on src/App.css
>  }
- [ ] You have done a pretty good job for adding the class like this to avoid repetition 🥇🥇However, as suggested by the reviewer [here](https://github.com/katfogy/bookstore-react/pull/6#discussion_r1232793238), kindly make sure to avoid repeating the same property multiple time ⛏🤓 For example, I can see that `display: flex` is repeating 7 time.

2023-06-17 00:00 UTC, KanzaTahreem commented on src/App.css
- [ ] Good job so far 🙌 However, as suggested by the reviewer [here](https://github.com/katfogy/bookstore-react/pull/6#discussion_r1232804683), kindly make sure that your design is EXACTLY the same as the one provided on Zeplin. You have done pretty good adjusting the `margins`, `color`, and `spacing` of all the elements 🤓⛏  but a little bit of more work is needed. See the images below for more clarity 💡 Kindly fix the highlighted area, also, kindly implement the following for getting a replica of the Zeplin design as mentioned earlier 💪
- [ ] Also, kindly note that book images have different styling, both books are taking different space ⚠
- [ ] The `background-color` looks a bit different than the one given in the design guidelines ⛏
- [ ] You have done a good job by adding the `box-shadow`, however, i is not present in the design guidelines, instead a border, `border: solid 1px #e8e8e8;`, is present 😅
- [ ] Kindly adjust the spacing of the book details and chapter details 📌
- [ ] Similarly, can you please adjust the spacing of the line between the circle (book progress) and chapter details, as you can see it is not in consistent with the given design

_Your design 👇_
![image](https://github.com/katfogy/bookstore-react/assets/106119105/cd5b6e7d-81e0-4282-8500-7219a6ef056d)

_Given design 👇_

![image](https://github.com/katfogy/bookstore-react/assets/106119105/1b900e33-6ac6-43ba-9d05-4cc2da599d53)

2023-06-17 08:31 UTC, Shisui6 approved these changes
Hi @katfogy, 

# Approved 🪄
Your project is complete! There is nothing else to say other than... it's time to merge it 💎
Congratulations! 🎉 

## Highlights 🎯
- Descriptive PR title and summary ✅
- Follows Github flow ✅
- Good commit messages ✅

## Optional suggestions 🪶

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-17 08:34 UTC, merged